version: '3.2'

services:
  php:
    build: ./deploy
    container_name: ce-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    tty: true

  db:
    image: postgres
    container_name: ce-db
    volumes:
      - ce-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ce-user
      POSTGRES_PASSWORD: ce-pwd
      POSTGRES_DB: ce_db
    ports:
      - 54320:5432
volumes:
  ce-db-volume:
    external: true
